package test.model;

import java.util.Date;
import javax.persistence.*;

@Table(name = "`yjk_member`")
public class YjkMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.id
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.nick_name
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.head_image
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private String headImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.moble
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private String moble;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.type
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.invite_code
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private String inviteCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.corporage_certification
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private Integer corporageCertification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.persion_certification
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private Integer persionCertification;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.status
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.companyname
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private String companyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.login_count
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private Integer loginCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.talk_id
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private String talkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.credit_score
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private Integer creditScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.create_time
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yjk_member.update_time
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.id
     *
     * @return the value of yjk_member.id
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.id
     *
     * @param id the value for yjk_member.id
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.nick_name
     *
     * @return the value of yjk_member.nick_name
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.nick_name
     *
     * @param nickName the value for yjk_member.nick_name
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.head_image
     *
     * @return the value of yjk_member.head_image
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public String getHeadImage() {
        return headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.head_image
     *
     * @param headImage the value for yjk_member.head_image
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setHeadImage(String headImage) {
        this.headImage = headImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.moble
     *
     * @return the value of yjk_member.moble
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public String getMoble() {
        return moble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.moble
     *
     * @param moble the value for yjk_member.moble
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setMoble(String moble) {
        this.moble = moble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.type
     *
     * @return the value of yjk_member.type
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.type
     *
     * @param type the value for yjk_member.type
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.invite_code
     *
     * @return the value of yjk_member.invite_code
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.invite_code
     *
     * @param inviteCode the value for yjk_member.invite_code
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.corporage_certification
     *
     * @return the value of yjk_member.corporage_certification
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public Integer getCorporageCertification() {
        return corporageCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.corporage_certification
     *
     * @param corporageCertification the value for yjk_member.corporage_certification
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setCorporageCertification(Integer corporageCertification) {
        this.corporageCertification = corporageCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.persion_certification
     *
     * @return the value of yjk_member.persion_certification
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public Integer getPersionCertification() {
        return persionCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.persion_certification
     *
     * @param persionCertification the value for yjk_member.persion_certification
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setPersionCertification(Integer persionCertification) {
        this.persionCertification = persionCertification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.status
     *
     * @return the value of yjk_member.status
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.status
     *
     * @param status the value for yjk_member.status
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.companyname
     *
     * @return the value of yjk_member.companyname
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.companyname
     *
     * @param companyname the value for yjk_member.companyname
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.login_count
     *
     * @return the value of yjk_member.login_count
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.login_count
     *
     * @param loginCount the value for yjk_member.login_count
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.talk_id
     *
     * @return the value of yjk_member.talk_id
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public String getTalkId() {
        return talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.talk_id
     *
     * @param talkId the value for yjk_member.talk_id
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setTalkId(String talkId) {
        this.talkId = talkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.credit_score
     *
     * @return the value of yjk_member.credit_score
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public Integer getCreditScore() {
        return creditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.credit_score
     *
     * @param creditScore the value for yjk_member.credit_score
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setCreditScore(Integer creditScore) {
        this.creditScore = creditScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.create_time
     *
     * @return the value of yjk_member.create_time
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.create_time
     *
     * @param createTime the value for yjk_member.create_time
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yjk_member.update_time
     *
     * @return the value of yjk_member.update_time
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yjk_member.update_time
     *
     * @param updateTime the value for yjk_member.update_time
     *
     * @mbg.generated Tue Aug 28 17:13:15 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}