#web server
server:
  port: 8086
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
#  jsp-servlet:
#    init-parameters:
#      development: true
logging:
  level:
    com: debug
spring:
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB
  #time format
  jackson:
    date-format: yyyy年MM月dd日
    time-zone: GMT+8
  #datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    ds1:
      #url: jdbc:mysql://localhost:3306/kzjx_dev?useUnicode=true&characterEncoding=utf8
      #username: root
      #password: 123456
      url: jdbc:mysql://gjhl.mysqldb.chinacloudapi.cn:3306/kzjx_dev?useUnicode=true&characterEncoding=utf8
      username: gjhl%zl
      password: zhanglei@2018
      driverClassName: com.mysql.jdbc.Driver
      name: datasource1
      #连接池建立时创建的初始化连接数
      initialSize: 5
      #连接池中最小连接数
      minIdle: 5
      #连接池中最大连接数
      maxActive: 20
      #获取连接时最大等待时间，单位是毫秒
      maxWait: 60000
      #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      #用来检测连接是否有效
      validationQuery: SELECT 1
      #是否在连接空闲一段时间后检测其可用性，申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
      testWhileIdle: true
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnBorrow: false
      #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      testOnReturn: false
      #是否缓存preparedStatement，也就是PSCache
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
    ds2:
      url: jdbc:mysql://localhost:3306/kzjx?useUnicode=true&characterEncoding=utf8
      username: gjhl%zl
      password: zhanglei@2018
      driverClassName: com.mysql.jdbc.Driver
      name: datasource2
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  redis:
    database: 0
    host: YunJiKuRedis.redis.cache.chinacloudapi.cn
    port: 6379
    password: /jq+6e4CyqOca8BSAZhv6XqcORRFLDSkqAVhc7V/dt4=
  activemq:
    broker-url: tcp://139.219.12.141:61616
    user: admin
    password: admin
    in-memory: true
    pool:
      enabled: false
  cache:
    type: ehcache

#mybatis
mybatis:
   configuration:
    mapUnderscoreToCamelCase: true
   mapperLocations: classpath:mapper/**/*.xml
   typeAliasesPackage: com.yjk.common.entity
   
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true

pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql

jwtvalidate:
    # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
    jwt:
        # 加密秘钥
        secret: gongchengjiiehulian2017
        # token有效时长，7天，单位秒
        expire: 2000000
        header: token  
solr:
  env: online
  url: http://42.159.83.118:8080/solr    
wx:
  mch_id: 1498445182
  apikey: 1145B1AFA2994480808B42793E486A81
  refundUrl: ${wx.xcx.baseUrl}/weixin/refund
  certUrl: /home/gchl/apiclient_cert.p12
  #certUrl: D:\BaiduNetdiskDownload\oldversionSandu\src\main\resources\apiclient_cert.p12
  xcx:
    #appid: wxe58b479e170a58a4
    #appSecret: 2b8ef2d84f12ebe6b8782877e894a84c
    accessToken: accessToken_pro
    appid: wxde59926deb607689
    appSecret: f7b774417e98b3d926d6d12e26db8a7d
    #服务器地址
    baseUrl: http://pay.huisonglin.top
    #baseUrl: http://127.0.0.1:8086
    #获取支付参数的地址
    accessPayParamUrl: ${wx.xcx.baseUrl}/weixin/xcx/unifiedorder
    tradeType: JSAPI
    xcxNotifyQueueName: vp
    page: pages/index/index
    fee: 1
    #获取openId的地址
    accessOpenIdUrl: ${wx.xcx.baseUrl}/weixin/xcx/generateOpenId
    #解密用户身份信息的地址
    decryptUserInfoUrl: ${wx.xcx.baseUrl}/weixin/xcx/decryptUserInfo
    #解密分享信息的地址
    decryptedShareInfo: ${wx.xcx.baseUrl}/weixin/xcx/decryptedShareInfo
    #解密用户手机号的地址
    decryptedPhoneNumber: ${wx.xcx.baseUrl}/weixin/xcx/decryptedPhoneNumber
    #获取accessToken地址
    accessTokendUrl: ${wx.xcx.baseUrl}/weixin/xcx/accessToken